#!/bin/bash
ACTION="$1"
shift
PACKAGE_LIST=$@

# START Define variables
DESTDOWNLOAD="/var/cache/epi-downloads"
# END Define Variables

# simplayer
# simplayer-phet-activitiestype
# simplayer-circuit
# simplayer-flash-activities
# simplayer-myphysicslab-activities
# kgeography
# kbruch
# kig
# kalgebra
# cantor
# kalzium
# kmplot
# rocs
# step

echo ACTION=$ACTION
echo PACKAGE_LIST=$PACKAGE_LIST

case $ACTION in
    getStatus)
        echo "getStatus ......"
        if [[ " ${PACKAGE_LIST[*]} " == *" simplayer "* ]]; then
            #echo 0
            #echo 1
            #echo "Not found"
            echo 
        fi
    ;;
        
    download)
        echo "Downloading ......"
        if [[ " ${PACKAGE_LIST[*]} " == *" simplayer "* ]]; then
            echo "Downloading simplayer......"
        fi
    ;;

    preInstall)
        echo "preInstall ......"
    ;;

    installPackage)
        echo "installPackage ......"
        if [[ " ${PACKAGE_LIST[*]} " == *" simplayer "* ]]; then
            echo " * * Start Installing simplayer * * "
            # apt install --install-recommends simplayer ... -y
            echo " * * Installed simplayer * * "
        elif [[ " ${PACKAGE_LIST[*]} " == *" simplayer-phet-activities "* ]]; then
            echo "Installing simplayer-phet-activities ... please wait"
            echo " * * Installed simplayer-phet-activities * * "
        fi
    ;;	

    postInstall)		
        echo "postInstall ......"
    ;;	

    remove)
        echo "remove ....."
        for ix in $PACKAGE_LIST; do
            if [[ " $ix " == *" simplayer "* ]]; then
                echo "Removing files from simplayer..."
                echo " * * Finished simplayer Uninstall * *  "
            elif [[ " $ix " == *" simplayer-phet-activities "* ]]; then
                echo "Removing files from simplayer-phet-activities..."
                echo " * * Finished simplayer-phet-activities Uninstall * * "
            else
                echo " * * Finished (other)* * "
            fi
        done		
    ;;	
esac

exit 0
